inherit_from: .rubocop_todo.yml

AllCops:
  TargetRubyVersion: 2.5.1

Style/StringLiterals:
  Exclude:
   - 'db/schema.rb'

Style/WordArray:
  Exclude:
    - 'db/schema.rb'

Style/MixinUsage:
  Exclude:
    - 'bin/setup'
    - 'bin/update'
    - 'spec/rails_helper.rb'

Style/Documentation:
  Enabled: false

Style/ClassAndModuleChildren:
  EnforcedStyle: compact

Metrics/AbcSize:
  Enabled: false

Metrics/ClassLength:
  Enabled: false

Metrics/CyclomaticComplexity:
  Enabled: false

Metrics/LineLength:
  Enabled: false

Metrics/MethodLength:
  Enabled: false

Metrics/ParameterLists:
  Enabled: false

Metrics/PerceivedComplexity:
  Enabled: false

Metrics/ModuleLength:
  Enabled: false

Metrics/BlockLength:
  Enabled: false

Metrics/LineLength:
  Enabled: false
