AllCops:
  TargetRubyVersion: 2.5.1
  Exclude:
    - 'db/schema.rb'
    - 'db/migrate/*'
    - 'bin/**/*'
    - 'lib/tasks/*'
    - 'vendor/**/*'
    - 'config/routes'
    - 'config/initializers/devise.rb'
    - 'config/initializers/active_admin.rb'
    - 'spec/rails_helper.rb'

Style/Documentation:
  Enabled: false

Style/ClassAndModuleChildren:
  EnforcedStyle: compact
  SupportedStyles:
    - nested
    - compact
  Exclude:
    - 'app/channels/application_cable/connection.rb'
    - 'app/channels/application_cable/channel.rb'
    - 'config/application.rb'
